.PHONY: run build test test-integration lint tidy

run:
	go run ./cmd/{{.Name}}

build:
	go build -o bin/{{.Name}} ./cmd/{{.Name}}

test:
	go test ./...

test-integration:
	docker compose -f deployments/docker-compose.test.yml up -d
	go test -tags=integration ./...

lint:
	golangci-lint run

tidy:
	go mod tidy

migrate-up:
	migrate -path migrations -database $(DATABASE_URL) up

migrate-down:
	migrate -path migrations -database $(DATABASE_URL) down 1
